version: 0.1
phases:
  install:
    commands:
      - pip3 install boto3
      - aws cloudformation package --template-file sample-sam.yml --s3-bucket serverless-app-sam-letitride --output-template-file sample-sam-output.yaml
artifacts:
  type: zip
  files:
    - sample-sam-output.yaml